### ISSUE TITLE
Less verbose output for cat_trauma?

### ISSUE THREAD

**Issue by BarkleyBG** [ablack3/icdpicr#1]
In running `cat_trauma()`, I'm getting a lot of messages:

    inserting columns for dx_1
    inserting columns for dx_2
    <etc>
    inserting columns for dx_n

Maybe the `cat_trauma()` could take a `verbose` argument? Setting `verbose = FALSE` would turn off these messages. 

If you'd like, I can code up this `verbose` argument and make a pull request. Thanks!

**Comment by ablack3** [comment]
Yes. I think those messages were primarily for helping me debug the program. I just went ahead and commented the message statements out. As long as the program works the messages aren't really that useful. For running `cat_trauma` on large datasets I suppose they can act as a progress indicator. 
However if users think a progress indicator would be helpful then I'll add a proper one instead of just printing a bunch of messages!

Thanks for the suggestion and let me know if there are any other improvements I can make. One thing that I need to do next is probably write some unit tests.
